version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bakery-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    networks:
      - bakery-network
    env_file:
      - ./backend/.env
    ports:
    - "8080:8000"

  mysql:
    image: mysql:8
    container_name: bakery-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bakery_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - bakery-network
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bakery-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - bakery-network

  # Vue Frontend (Node.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bakery-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks:
      - bakery-network
    depends_on:
      - backend

networks:
  bakery-network:
    driver: bridge

volumes:
  mysql_data:
